include: package:pedantic/analysis_options.1.8.0.yaml
linter:
  rules:
    prefer_relative_imports: true
    prefer_const_declarations: true
    prefer_const_constructors: true
    unnecessary_const: true
